name: Bakana

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
    - name: Test
      env:
        SERVICESTACK_LICENSE: ${{ secrets.SERVICESTACK_LICENSE }}
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./src
    - name: Nuget Pack Bakana.CLI
      run: dotnet pack ./src/Bakana.CLI/Bakana.CLI.csproj --output nuget-packages --configuration Release
      working-directory: ./src/Bakana.CLI
    - name: Publish Bakana.CLI to Nuget
      run: dotnet nuget push ./nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
